import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import './globals.css';
import { Menu } from '@/widgets/Menu/Menu';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={
          outfit.className +
          ' container pl-8 pr-9 py-8 grid grid-cols-layout gap-9'
        }>
        <aside>
          <Menu />
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
