import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import '@/styles/globals.css';

import { Menu } from '@/widgets';
import { Search } from '@/components';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={outfit.className + ' custom-container'}>
        <aside className='col-start-[sidebar-start] row-start-1 row-end-[-1]'>
          <Menu />
        </aside>
        <div className='col-start-[main-start]'>
          <Search />
        </div>
        <main className='col-start-[main-start] col-end-[end] grid grid-cols-subgrid gap-y-10'>
          {children}
        </main>
      </body>
    </html>
  );
}
