import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import '@/styles/globals.css';

import { Menu } from '@/widgets';
import { Search } from '@/components';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={
          outfit.className +
          ' container pl-8 pr-9 py-8 grid grid-cols-layout grid-rows-[auto_1fr] gap-9'
        }>
        <aside className='col-start-1 row-start-1 row-end-3'>
          <Menu />
        </aside>
        <div className='col-start-2'>
          <Search />
        </div>
        <main className='col-start-2'>{children}</main>
      </body>
    </html>
  );
}
